### ISSUE TITLE
Home page can be opened, but after landing, there is a white page, is the bug?

### ISSUE THREAD

**Issue by hucocohu** [socioboard/socioboard-core#47] opened 2017-10-17 04:17 UTC
Home page can be opened, but after landing, there is a white page, is the bug?
1 home page:
![qq 20171017115848](https://user-images.githubusercontent.com/29749535/31646123-89a08e46-b332-11e7-9305-5c928dc04fa8.png)
2 landing:
![qq 20171017115959](https://user-images.githubusercontent.com/29749535/31646161-c778929a-b332-11e7-81fc-34cc768c9357.png)
3 after landing:

![qq 20171017120221](https://user-images.githubusercontent.com/29749535/31646287-940979f0-b333-11e7-8219-43b69e71e1fe.png)

thank you

**Comment by socioboard** [comment] 2017-11-07 07:48
Hi hucocohu,
No its not a bug ,try with latest release socioboard3.0 version
https://github.com/socioboard/Socioboard-Core-3.0/releases
in case if you facing problem please let us know 

Thanks 
SB team

**Comment by socioboard** [comment] 2018-02-16 05:33
Hi hucocohu,
I hope you have find your solution .for now am closing this issue if you have any prob regarding code 
please let us know .

Thanks 
SB team

**Closed as completed** 2018-02-16 05:48 UTC
